config/routes.rb
Rails.application.routes.draw do

  resources :clas

  resources :groups

  resources :courses

  resources :professors

  resources :rooms

  root 'courseevents#index'

end

app/models/cla.rb
class Cla < ActiveRecord::Base
	has_one :professor    	
	has_one :course
	has_many :cla_groups
	has_many :groups , :through => :cla_groups, :dependent => :destroy

	def professor_name
		professor.tname if professor
	end
   def course_name
		course.tname if course
	end
	 
	
end

app/controllers/clas_controller.rb
class ClasController < ApplicationController
  before_action :set_cla, only: [:show, :edit, :update, :destroy]

  # GET /clas
  # GET /clas.json
  def index
    @clas = Cla.all
  end

  # GET /clas/1
  # GET /clas/1.json
  def show
  end

  # GET /clas/new
  def new
    @cla = Cla.new
  end

  # GET /clas/1/edit
  def edit
  end

  # POST /clas
  # POST /clas.json
  def create
    @cla = Cla.new(cla_params)

    respond_to do |format|
      if @cla.save
        format.html { redirect_to @cla, notice: 'Cla was successfully created.' }
        format.json { render :show, status: :created, location: @cla }
      else
        format.html { render :new }
        format.json { render json: @cla.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clas/1
  # PATCH/PUT /clas/1.json
  def update
    respond_to do |format|
      if @cla.update(cla_params)
        format.html { redirect_to @cla, notice: 'Cla was successfully updated.' }
        format.json { render :show, status: :ok, location: @cla }
      else
        format.html { render :edit }
        format.json { render json: @cla.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clas/1
  # DELETE /clas/1.json
  def destroy
    @cla.destroy
    respond_to do |format|
      format.html { redirect_to clas_url, notice: 'Cla was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cla
      @cla = Cla.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cla_params
      params.require(:cla).permit(:professor_id, :course_id,  :duration, :lab, :group_ids => [])
    end
end

app/helpers/clas_helper.rb
module ClasHelper
end

app/views/clas/_form.html.erb
<%= form_for(@cla) do |f| %>
  <% if @cla.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cla.errors.count, "error") %> prohibited this cla from being saved:</h2>

      <ul>
      <% @cla.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :professor_id %><br>
    <%=  f.number_field  :professor_id %> 
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.number_field  :course_id %> 
  </div>
  <div class="field">
    <%= f.label :group_id %><br>
    <%= f.select :group_ids, Group.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %>
              
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :lab %><br>
    <%= f.check_box :lab %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clas/edit.html.erb
<h1>Editing cla</h1>

<%= render 'form' %>

<%= link_to 'Show', @cla %> |
<%= link_to 'Back', clas_path %>

app/views/clas/index.html.erb
<h1>Listing clas</h1>

<table>
  <thead>
    <tr>
      <th>Professor</th>
      <th>Course</th>
      <th>  Group</th>
      <th>Duration</th>
      <th>Lab</th>
      <th>ClaGroup</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clas.each do |cla| %>
      <tr>
        <td><%= cla.professor_id %></td>
        <td><%= cla.course_id %></td>
        <td> <dd><%= cla.groups.map(&:name).join(', ')  %></dd></td>
        <td><%= cla.duration %></td>
        <td><%= cla.lab %></td>
        <td><%= cla.groups.map(&:id).join(', ') %></td>
        <td><%= link_to 'Show', cla %></td>
        <td><%= link_to 'Edit', edit_cla_path(cla) %></td>
        <td><%= link_to 'Destroy', cla, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cla', new_cla_path %>

app/views/clas/new.html.erb
<h1>New cla</h1>

<%= render 'form' %>

<%= link_to 'Back', clas_path %>

app/views/clas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Professor:</strong>
  <%= @cla.professor_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @cla.course_id %>
</p>

<p>
  <strong>Group:</strong>
  <dd> <%= @cla.groups.map(&:name).join(', ') %></dd>
</p>

<p>
  <strong>Duration:</strong>
  <%= @cla.duration %>
</p>

<p>
  <strong>Lab:</strong>
  <%= @cla.lab %>
</p>

<%= link_to 'Edit', edit_cla_path(@cla) %> |
<%= link_to 'Back', clas_path %>