config/routes.rb
Rails.application.routes.draw do

  resources :clas

  resources :groups

  resources :courses

  resources :professors

  resources :rooms

  root 'courseevents#index'

end

app/models/courseevent.rb
class Courseevent < ActiveRecord::Base
  belongs_to :cbrcase
end

app/controllers/courseevents_controller.rb
class CourseeventsController < ApplicationController
  def index
  	#c = Algorithm.new
   # @c = Schedule.new.res
  	#gon.courseevents = Courseevent.order(:id)
     @courseevents = Courseevent.order(:id)
     @rooms = Room.order(:id)
     
  end

   
end

app/views/courseevents/index.html.erb
<h1>Schedule</h1>
 

 
<table>
  <thead>
    <tr>                                                                                                                                                                                                                                                                                                                                                                                                                          
      <th>Roomname</th>
       <th>Lab</th>
        <th>meetingtime</th>
       <th>meetingday</th>
      <th>courseduration</th>
       <th>coursename</th>
        <th>profname</th>
             <th>groupname</th>
        <th>cbrcase_id</th> 
      <th colspan="3"></th>                                                                                               
    </tr>
  </thead>
<tbody> 
<div id="placeholder"></div>

 <div id: "courseevents">
     <% @courseevents.each do |courseevent| %>
      <tr>

        <td><%= courseevent.roomname %></td>
        <td><%= courseevent.lab %></td>
        <td><%= courseevent.meetingtime %></td>
        <td><%= courseevent.meetingday %></td>
        <td><%= courseevent.courseduration %></td>
        <td><%= courseevent.coursename %></td>
        <td><%= courseevent.profname %></td>
        <td><%= courseevent.groupname %></td>
        <td><%= courseevent.cbrcase_id %></td>
        
  </tr>

 <% end %>

  </div>
  <%= content_tag :div, class: "courseevents_class", data: {courseevents: @courseevents} do %>
<% end %>
<%= content_tag :div, class: "rooms_class", data: {rooms: @rooms} do %>
<% end %>
</tbody>
</table>

<br>

<%= link_to 'New Cla', new_cla_path %>
<%= link_to 'New Professor', new_professor_path %>
<%= link_to 'New Group', new_group_path %>
<%= link_to 'New Course', new_course_path %>